name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          tags: ghcr.io/benoitsemifir/volcano-api:$(date +%s)
          push: true
